/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cYtFYdVtykXpyPSmJwBtNk

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsrbjbd6IxmKjb } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: rbjbd6IxmKJB/globalVariant
import { ScheduleValue, useSchedule } from "./PlasmicGlobalVariant__Schedule"; // plasmic-import: 0ExYue8SfpwG/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsrbjbd6IxmKjb,
  schedule: useSchedule
});
