/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cYtFYdVtykXpyPSmJwBtNk
// Component: mniyWgBlKijO

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { NavigationBar } from "@plasmicpkgs/plasmic-nav";

import { useScreenVariants as useScreenVariantsrbjbd6IxmKjb } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: rbjbd6IxmKJB/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: cYtFYdVtykXpyPSmJwBtNk/projectcss
import sty from "./PlasmicImpressum.module.css"; // plasmic-import: mniyWgBlKijO/css

import Call24DpE8EaedFill1Wght400Grad0Opsz24SvgIcon from "./icons/PlasmicIcon__Call24DpE8EaedFill1Wght400Grad0Opsz24Svg"; // plasmic-import: QlL3tTqfAw4N/icon
import Mail24DpE8EaedFill1Wght400Grad0Opsz24SvgIcon from "./icons/PlasmicIcon__Mail24DpE8EaedFill1Wght400Grad0Opsz24Svg"; // plasmic-import: RS4xpgiJxFif/icon
import Instagram3SvgIcon from "./icons/PlasmicIcon__Instagram3Svg"; // plasmic-import: FenFes5YFI20/icon
import TiktokSvgIcon from "./icons/PlasmicIcon__TiktokSvg"; // plasmic-import: TIFQAripOqvN/icon
import Facebook3SvgIcon from "./icons/PlasmicIcon__Facebook3Svg"; // plasmic-import: RJ2yhi0BbV-9/icon

createPlasmicElementProxy;

export type PlasmicImpressum__VariantMembers = {};
export type PlasmicImpressum__VariantsArgs = {};
type VariantPropType = keyof PlasmicImpressum__VariantsArgs;
export const PlasmicImpressum__VariantProps = new Array<VariantPropType>();

export type PlasmicImpressum__ArgsType = {};
type ArgPropType = keyof PlasmicImpressum__ArgsType;
export const PlasmicImpressum__ArgProps = new Array<ArgPropType>();

export type PlasmicImpressum__OverridesType = {
  root?: Flex__<"div">;
  navigacija?: Flex__<typeof NavigationBar>;
  izaberiteTemuVaseCarobneZabave?: Flex__<"section">;
  h2?: Flex__<"h2">;
  footer?: Flex__<"section">;
  impressum?: Flex__<"a"> & Partial<LinkProps>;
  politikaPrivatnosti?: Flex__<"a"> & Partial<LinkProps>;
  freeBox?: Flex__<"div">;
  section?: Flex__<"section">;
};

export interface DefaultImpressumProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicImpressum__RenderFunc(props: {
  variants: PlasmicImpressum__VariantsArgs;
  args: PlasmicImpressum__ArgsType;
  overrides: PlasmicImpressum__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsrbjbd6IxmKjb()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <NavigationBar
            data-plasmic-name={"navigacija"}
            data-plasmic-override={overrides.navigacija}
            brand={
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__mnJ3
                )}
                component={Link}
                href={`/`}
                platform={"nextjs"}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__eNpMe)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "mobile")
                      ? "70px"
                      : "90px"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  src={{
                    src: "/plasmic/princess_maddy/images/princessMaddyLogoPng.png",
                    fullWidth: 1459,
                    fullHeight: 875,
                    aspectRatio: undefined
                  }}
                />
              </PlasmicLink__>
            }
            className={classNames("__wab_instance", sty.navigacija)}
            closeButton={
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__uYcee)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                src={"https://static1.plasmic.app/close.svg"}
              />
            }
            itemsGap={8}
            menuItems={
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__vZ6AR
                )}
                component={Link}
                href={`/`}
                platform={"nextjs"}
              >
                {"Naslovnica"}
              </PlasmicLink__>
            }
            openButton={
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__yDSy)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobile")
                    ? "40px"
                    : "auto"
                }
                src={"https://static1.plasmic.app/menu.svg"}
              />
            }
            responsiveBreakpoint={768}
          />

          <section
            data-plasmic-name={"izaberiteTemuVaseCarobneZabave"}
            data-plasmic-override={overrides.izaberiteTemuVaseCarobneZabave}
            className={classNames(
              projectcss.all,
              sty.izaberiteTemuVaseCarobneZabave
            )}
          >
            <h2
              data-plasmic-name={"h2"}
              data-plasmic-override={overrides.h2}
              className={classNames(
                projectcss.all,
                projectcss.h2,
                projectcss.__wab_text,
                sty.h2
              )}
            >
              {"Impressum"}
            </h2>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__tNkzf
              )}
            >
              <React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"Naziv obrta/djelatnosti:"}
                </span>
                <React.Fragment>
                  {"\nFirefly, obrt za savjetovanje u poslovanju\n\n"}
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"Vlasnica:"}
                </span>
                <React.Fragment>
                  {"\nMadelyn Wills \u010celikovi\u0107\n\n"}
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"Adresa sjedi\u0161ta:"}
                </span>
                <React.Fragment>
                  {
                    "\nGunduli\u0107eva 23,\n35400 Nova Gradi\u0161ka, Hrvatska\n\n"
                  }
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"Kontakt:"}
                </span>
                <React.Fragment>
                  {
                    "\nTelefon: +385 99 736 1551\nE-mail: info@animatorica-princess-maddy.com\nWeb: www.animatorica-princess-maddy.com\n\n"
                  }
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"OIB:"}
                </span>
                <React.Fragment>{"\n73598771799\n\n"}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"IBAN:\u00a0"}
                </span>
                <React.Fragment>{"\nHR2723600001103041883\n\n"}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"Oblik poslovanja:"}
                </span>
                <React.Fragment>
                  {
                    "\nSamostalna djelatnost (obrt) \u2013 upisana u Obrtni registar RH\n\n"
                  }
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"Odgovorna osoba za sadr\u017eaj stranice:"}
                </span>
                <React.Fragment>{"\nRomana Miler\n\n"}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"Nadle\u017eno tijelo:"}
                </span>
                <React.Fragment>
                  {
                    "\nMinistarstvo gospodarstva i odr\u017eivog razvoja Republike Hrvatske\n\n"
                  }
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"Autorska prava:"}
                </span>
                <React.Fragment>
                  {
                    "\nSvi sadr\u017eaji (tekstovi, slike, video zapisi) na ovoj stranici su autorsko vlasni\u0161tvo Firefly-a, osim ako nije druga\u010dije nazna\u010deno. Zabranjeno je kopiranje i distribuiranje bez prethodnog odobrenja."
                  }
                </React.Fragment>
              </React.Fragment>
            </div>
          </section>
          <section
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames(projectcss.all, sty.footer)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__qW93D)}
            >
              <div className={classNames(projectcss.all, sty.column__bzcuS)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__eWqIs)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobile")
                      ? "50%"
                      : hasVariant(globalVariants, "screen", "tablet")
                      ? "100%"
                      : hasVariant(globalVariants, "screen", "smallDesktop")
                      ? "80%"
                      : "90%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/princess_maddy/images/princessMaddyLogoPng.png",
                    fullWidth: 1459,
                    fullHeight: 875,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___0QVxh)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__kPix
                  )}
                >
                  {"Kontakt"}
                </h4>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__cdMyA)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__mR2Iu)}
                  >
                    <Call24DpE8EaedFill1Wght400Grad0Opsz24SvgIcon
                      className={classNames(projectcss.all, sty.svg__msHz2)}
                      role={"img"}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__z4Qz5)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__c7Lje
                      )}
                    >
                      {"099 736 1551"}
                    </div>
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__hhqY)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__aeeLp)}
                  >
                    <Mail24DpE8EaedFill1Wght400Grad0Opsz24SvgIcon
                      className={classNames(projectcss.all, sty.svg___7B7Ue)}
                      role={"img"}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__lZlSr)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__dgYxQ
                      )}
                      component={Link}
                      href={"mailto:info@animatorica-princess-maddy.com"}
                      platform={"nextjs"}
                    >
                      {hasVariant(globalVariants, "screen", "smallDesktop")
                        ? "info@animatorica-princess-maddy.com"
                        : "info@animatorica-princess-maddy.com"}
                    </PlasmicLink__>
                  </div>
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__qNqg)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__aPth8
                  )}
                >
                  {"Stranice"}
                </h4>
                <PlasmicLink__
                  data-plasmic-name={"impressum"}
                  data-plasmic-override={overrides.impressum}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.impressum
                  )}
                  component={Link}
                  href={`/impressum`}
                  platform={"nextjs"}
                >
                  {hasVariant(globalVariants, "screen", "smallDesktop")
                    ? "Impressum"
                    : "Impressum"}
                </PlasmicLink__>
                <PlasmicLink__
                  data-plasmic-name={"politikaPrivatnosti"}
                  data-plasmic-override={overrides.politikaPrivatnosti}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.politikaPrivatnosti
                  )}
                  component={Link}
                  href={`/politika-privatnosti`}
                  platform={"nextjs"}
                >
                  {hasVariant(globalVariants, "screen", "smallDesktop")
                    ? "Politika privatnosti"
                    : "Politika privatnosti"}
                </PlasmicLink__>
              </div>
              <div className={classNames(projectcss.all, sty.column__z3Pmd)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__yNqJ
                  )}
                >
                  {"Pratite me!"}
                </h4>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"freeBox"}
                  data-plasmic-override={overrides.freeBox}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox)}
                >
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__br3A7
                    )}
                    component={Link}
                    href={
                      "https://www.instagram.com/princess____maddy?igsh=MW16NHV2cG01MDc1aA=="
                    }
                    platform={"nextjs"}
                    target={"_blank"}
                  >
                    <Instagram3SvgIcon
                      className={classNames(projectcss.all, sty.svg__rMjV)}
                      role={"img"}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__wym3N
                    )}
                    component={Link}
                    href={"https://www.tiktok.com/@partyprincessmaddy"}
                    platform={"nextjs"}
                    target={"_blank"}
                  >
                    <TiktokSvgIcon
                      className={classNames(projectcss.all, sty.svg__bNyJk)}
                      role={"img"}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__ojxNi
                    )}
                    component={Link}
                    href={"https://www.facebook.com/share/16HpvQNQiQ/"}
                    platform={"nextjs"}
                    target={"_blank"}
                  >
                    <Facebook3SvgIcon
                      className={classNames(projectcss.all, sty.svg__vEjwh)}
                      role={"img"}
                    />
                  </PlasmicLink__>
                </Stack__>
              </div>
            </Stack__>
            <section
              data-plasmic-name={"section"}
              data-plasmic-override={overrides.section}
              className={classNames(projectcss.all, sty.section)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wSkvN
                )}
              >
                {"\u00a9 2025 Firefly. Sva prava pridr\u017eana. "}
              </div>
            </section>
          </section>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navigacija",
    "izaberiteTemuVaseCarobneZabave",
    "h2",
    "footer",
    "impressum",
    "politikaPrivatnosti",
    "freeBox",
    "section"
  ],
  navigacija: ["navigacija"],
  izaberiteTemuVaseCarobneZabave: ["izaberiteTemuVaseCarobneZabave", "h2"],
  h2: ["h2"],
  footer: ["footer", "impressum", "politikaPrivatnosti", "freeBox", "section"],
  impressum: ["impressum"],
  politikaPrivatnosti: ["politikaPrivatnosti"],
  freeBox: ["freeBox"],
  section: ["section"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navigacija: typeof NavigationBar;
  izaberiteTemuVaseCarobneZabave: "section";
  h2: "h2";
  footer: "section";
  impressum: "a";
  politikaPrivatnosti: "a";
  freeBox: "div";
  section: "section";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicImpressum__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicImpressum__VariantsArgs;
    args?: PlasmicImpressum__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicImpressum__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicImpressum__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicImpressum__ArgProps,
          internalVariantPropNames: PlasmicImpressum__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicImpressum__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicImpressum";
  } else {
    func.displayName = `PlasmicImpressum.${nodeName}`;
  }
  return func;
}

export const PlasmicImpressum = Object.assign(
  // Top-level PlasmicImpressum renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navigacija: makeNodeComponent("navigacija"),
    izaberiteTemuVaseCarobneZabave: makeNodeComponent(
      "izaberiteTemuVaseCarobneZabave"
    ),
    h2: makeNodeComponent("h2"),
    footer: makeNodeComponent("footer"),
    impressum: makeNodeComponent("impressum"),
    politikaPrivatnosti: makeNodeComponent("politikaPrivatnosti"),
    freeBox: makeNodeComponent("freeBox"),
    section: makeNodeComponent("section"),

    // Metadata about props expected for PlasmicImpressum
    internalVariantProps: PlasmicImpressum__VariantProps,
    internalArgProps: PlasmicImpressum__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicImpressum;
/* prettier-ignore-end */
